services:
    api:
      build:
        context: .
        dockerfile: ./containers/api/Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - "./workspaces:/app/workspaces"
        - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
        - HOST_WORKSPACE_PATH=${PWD}/workspaces

    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"